### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ThisIsQasim** [makleso6/homebridge-broadlink-heater-cooler#1]
I am looking for a working homebridge plugin for a broadlink device. Would you mind updating the readme to mention what this plugin does (and doesn't). Thanks

**Comment by makleso6** [comment]
@ThisIsQasimThis plugin only support AirConditioner

**Comment by ThisIsQasim** [comment]
That is what I am looking for. I have an AirConditioner with built in broadlink module and comes with an app named AC Freedom. The app sucks so I am looking for alternative ways to control the AC. As far as I know broadlink-rm is different from what I have.

**Comment by makleso6** [comment]
Yes, my plugin compatible with AirConditioner working via AC Freedom

**Comment by makleso6** [comment]
I'll write readme soon, when it finally works fine)

**Comment by makleso6** [comment]
Try it, I write simple README.MD

**Comment by ThisIsQasim** [comment]
Just tried the plugin with a Kenwood AirConditioner (eSmart 1820s) which works with the AC Freedom app and it works. I am however seeing a couple of issues. 

1) I don't see a way to turn the display off.
2) The ambient temperature isn't correctly reported (always 22 C).
3) AC starts beeping whenever I go in to accessory details.
4) Adjusting the fan speed slider turns on oscillation.

**Comment by makleso6** [comment]
@ThisIsQasim `1. I don't see a way to turn the display off.` It is not implemented. Hope I can make it soon.
`2. The ambient temperature isn't correctly reported (always 22 C).`. I can't find way to get temperature :(
`3. AC starts beeping whenever I go in to accessory details.` I think HomeKit send some data when go to detail.
`4. Adjusting the fan speed slider turns on oscillation.`. I think it is bug, Try to fix it :)

**Comment by ThisIsQasim** [comment]
1) Since I always have the display set to off, I changed the hardcoded display=1 to display=0 and that is no longer an issue.
2) Is there any way to query the AC for temperature? The broadlink rm module which you suggested earlier can read temp from a file. Can we maybe setup a cron that queries the temperature from the AC every minute and writes it to a file. Your module can then read the temperature from the file?
3) Can you investigate?
4) Thanks :)

**Comment by makleso6** [comment]
2. I think it is no possible
3. My AC is broken now(
