### ISSUE TITLE
Temperature request without decimals

### ISSUE THREAD

**Issue by fparrav** [makleso6/homebridge-broadlink-heater-cooler#10]
**Is your feature request related to a problem? Please describe:**

No, currently I don't see any problem

**Describe the solution you'd like:**

{
            "accessory": "AirCondionerAccessory",
            "ip": "192.168.1.76",
            "mac": "34:ea:34:96:e7:05",
            "name": "AirCon",
            "increments": 0.5 or 1.0
 }

**Describe alternatives you've considered:**

N/A
**Additional context:**

In my country it is not customary to control the temperature with decimals, the remote control increases and reduces the temperature in whole numbers

**Comment by makleso6** [comment]
Ok, try to add it

**Comment by makleso6** [comment]
@fparrav please check

**Comment by makleso6** [comment]
My remote also  control increases and reduces the temperature in whole numbers too, but I can do it in ACFreedom app

**Comment by fparrav** [comment]
Thanks !, it works perfectly!.
