### ISSUE TITLE
Проблемы с использованием дефиса в именах параметров

### ISSUE THREAD

**Issue by Romak82** [makleso6/homebridge-broadlink-heater-cooler#19]
Проблема появилась при переходе на последнюю версию.
Параметры **CurrentHeater-CoolerState** и **TargetHeater-CoolerState** раньше не имели дефисов.
Проблема с дефисом возникает при использовании _Homebridge_ в связке с _Node-RED_.
Если в _Node-RED_ использовать функцию, в которой принимается данный параметр, например:
`var y = msg.payload.CurrentHeater-CoolerState;`
то происходит ошибка при исполнении, дефис воспринимается как перенос строки.
Можно использовать костыль в виде предварительного дублирования содержимого **msg.payload.CurrentHeater-CoolerState** например в **msg.payload.CurrentHeaterCoolerState** и уже новый объект использовать в своей функции. Но это лишние вычислительные затраты при регулярном опросе статуса.

Если можно, хотелось бы вернуться к наименованию параметров без использования символов. Или использование именно таких наименований продиктовано политикой _HomeKit_?

**Comment by Romak82** [comment]
Нашел другой способ обойти проблему.
При наличии в наименовании объектов специальных символов, необходимо использовать следующий синтаксис _Javascript_:
`var y = msg.payload["CurrentHeater-CoolerState"];`
вместо
`var y = msg.payload.CurrentHeater-CoolerState;`

**Comment by makleso6** [comment]
@Romak82 Привет!
 для NodeRed можно использовать этот плагин 
https://github.com/makleso6/broadlink-aircon-api/blob/master/src/index.ts
там вся бизнес логика

**Comment by funnymataleao** [comment]
@makleso6 Привет. В итоге плагин сейчас не работает, да?

**Comment by makleso6** [comment]
@funnymataleao Привет. Плагин работает (на Homebridge точно)

**Comment by funnymataleao** [comment]
Привет. Странно. Я вчера фиг знает сколько времени на него убил и так и не завелся. В приложении от Broadlink Кондей отлично работает, в  Homekit пробрасывается, но при включении в хомките ничего не происходит. IP и Mac адреса точные вставил. В чем может быть проблема? Сейчас опять попробую его завести.

**Comment by funnymataleao** [comment]
Может я все неправильно делаю, потому что вставляю IP самого  Broadlink,  а не IP дочернего устройства, в данном случае кондиционера? Я когда захожу в информацию об устройстве самого кондея, то он не показывает его  IP и пишет - "Получить информацию не удалось. Нажмите, чтобы повторить попытку". Нажимаешь и ничего не появляется.

**Comment by funnymataleao** [comment]
Хотя нет, только что еще раз проверил - IP и Mac верные, да и конфигурации абсолютно такой же, как и вот [тут](https://github.com/makleso6/homebridge-broadlink-heater-cooler#readme), но ничего не работает, в Homekit он появляется, но кнопки никак не реагируют и при этом в приложении  Broadlink  все отлично работает.

**Comment by makleso6** [comment]
@funnymataleao в самом кондиционере есть модуль WiFi? или управление осуществляется через ИК?

**Comment by funnymataleao** [comment]
Да, конечно. Через LG Things он отлично работает.

**Comment by makleso6** [comment]
@funnymataleao Этот плагин не работает с LG Things, только ACFreedom

**Comment by funnymataleao** [comment]
Эх, блин. Значит я зря время потратил? 😢
