### ISSUE TITLE
Need some help :) 

### ISSUE THREAD

**Issue by javimoralez** [makleso6/homebridge-broadlink-heater-cooler#2]
Hi, I’m newbie on all this homebridge stuff, I was wondering if you could help me to get to work this plugin with my AC, I tried others and they just don’t get installed, and for some reason yours gets installed amazingly, so what I don’t understand is how my json file needs to be so I can have full control of my ac, I just have what I found on your readme file, but that’s it, so I’m looking for some guidance with this plugin, I honestly haven’t done anything like this in the past, and I would love to get some help. Regards!

**Comment by makleso6** [comment]
What kind of AC do you use?
Can you add your AC in iOS app ACFreedom?

**Comment by javimoralez** [comment]
It’s a dumb ac, I wanted to use a broadlink mini 4 that I have already installed, I cannot run the other plugins on my homebridge, yours was installed though.
I tried with the ac freedom and it didn’t work 😅.
Regards


Enviado desde mi iPhone

El 20 abr 2020, a la(s) 4:38, Maxim Kolesnik <notifications@github.com> escribió:

﻿

What kind of AC do you use?
Can you add your AC in iOS app ACFreedom?

**Comment by makleso6** [comment]
Sorry, this plugin only for AC compatible with ACFreedom
