### ISSUE TITLE
Ambient temperature?

### ISSUE THREAD

**Issue by ThisIsQasim** [makleso6/homebridge-broadlink-heater-cooler#3]
The ambient temperature (current room temperature) is always shown as 22C. Since the AC Freedom app can get the ambient temperature, I am sure there must be a way for this plugin to get the ambient temperature. I can see some references in the code to 
`tempNow` but it doesn’t seem to be used anywhere. Can you investigate?

**Comment by makleso6** [comment]
I Know this bug

**Comment by ThisIsQasim** [comment]
I was the one who reported it last time 😅

**Comment by ThisIsQasim** [comment]
@makleso6 so any plan to work on it? If don’t have an AC I can give you access via VPN

**Comment by makleso6** [comment]
I have AC
But I don't know how to get temperature
also see
https://github.com/liaan/broadlink_ac_mqtt/issues/1

**Comment by liaan** [comment]
Just update my code ... welcome to have look, you need to send a different command for the info .. did not spend to much time to verify the data, but running it now on my enviroment (2 aircons) so will report back

**Comment by liaan** [comment]
> Just update my code ... welcome to have look, you need to send a different command for the info .. did not spend to much time to verify the data, but running it now on my enviroment (2 aircons) so will report back

Ok.. been running for while, seems to be working correctly. I will still check if there decimal values somewhere , but for now its only whole numbers

**Comment by taimurasad** [comment]
@liaan can you please tell me what you did to get multiple ACs (2 aircons) working? Also, can will be great if you could also tell how you fixed and got ambient temperature working?


> > Just update my code ... welcome to have look, you need to send a different command for the info .. did not spend to much time to verify the data, but running it now on my enviroment (2 aircons) so will report back
> 
> Ok.. been running for while, seems to be working correctly. I will still check if there decimal values somewhere , but for now its only whole numbers

**Comment by liaan** [comment]
> @liaan can you please tell me what you did to get multiple ACs (2 aircons) working? Also, can will be great if you could also tell how you fixed and got ambient temperature working?
> 
> 
> Just update my code ... welcome to have look, you need to send a different command for the info .. did not spend to much time to verify the data, but running it now on my enviroment (2 aircons) so will report back
> 
> Ok.. been running for while, seems to be working correctly. I will still check if there decimal values somewhere , but for now its only whole numbers

Hi,  I don't look after this library, so not sure .... 
 I can help you with the MQTT library at https://github.com/liaan/broadlink_ac_mqtt , it does multiple AC's by default and ambient works for most AC's

**Comment by taimurasad** [comment]
> > @liaan can you please tell me what you did to get multiple ACs (2 aircons) working? Also, can will be great if you could also tell how you fixed and got ambient temperature working?
> > Just update my code ... welcome to have look, you need to send a different command for the info .. did not spend to much time to verify the data, but running it now on my enviroment (2 aircons) so will report back
> > Ok.. been running for while, seems to be working correctly. I will still check if there decimal values somewhere , but for now its only whole numbers
> 
> Hi, I don't look after this library, so not sure ....
> I can help you with the MQTT library at https://github.com/liaan/broadlink_ac_mqtt , it does multiple AC's by default and ambient works for most AC's

Is https://github.com/liaan/broadlink_ac_mqtt a Homebridge plugin? Sorry but I’m clueless as to how do i install on this on my Homebridge image-running Pi. Can you provide a basic explanation on how to get it working? Thank you

**Comment by liaan** [comment]
> @liaan can you please tell me what you did to get multiple ACs (2 aircons) working? Also, can will be great if you could also tell how you fixed and got ambient temperature working?
> Just update my code ... welcome to have look, you need to send a different command for the info .. did not spend to much time to verify the data, but running it now on my enviroment (2 aircons) so will report back
> Ok.. been running for while, seems to be working correctly. I will still check if there decimal values somewhere , but for now its only whole numbers
> 
> Hi, I don't look after this library, so not sure ....
> I can help you with the MQTT library at https://github.com/liaan/broadlink_ac_mqtt , it does multiple AC's by default and ambient works for most AC's
> 
> Is https://github.com/liaan/broadlink_ac_mqtt a Homebridge plugin? Sorry but I’m clueless as to how do i install on this on my Homebridge image-running Pi. Can you provide a basic explanation on how to get it working? Thank you

Nope, its not a homebridge plugin.  Its a separate process that runs and puts the AC details onto MQTT.

**Comment by fparrav** [comment]
The lack of the current temperature generates an erratic behavior in homekit, when requesting a temperature it could wrongly activate the heat or cold mode. 

for now the @liaan  plugin is the best option ... install [home assistant in docker](https://www.home-assistant.io/docs/installation/docker/), run `monitor.py` with PM2 and in home assistant there is the integration of a homekit bridge, it works without problems.

it would be ideal if this could be corrected, since it is much lighter for my raspberry to run homebridge than home assistant only for one device.

**Comment by liaan** [comment]
Another method maybe , use mqtt thing  for homebridge https://www.npmjs.com/package/homebridge-mqtt

**Comment by liaan** [comment]
Another option to use mqtt thing ? https://www.npmjs.com/package/homebridge-mqttthing

**Comment by jackscorpse** [comment]
> Another option to use mqtt thing ? https://www.npmjs.com/package/homebridge-mqttthing

I had problems with the mqttthing plugin settings - turning on and off does not work with my AC, the fan speed adjustment does not work, the ambient temperature sometimes updated, sometimes not. If I set "HomeKit" topics in mqttthing settings then temperature resets to 25, can't change it, "Home Assistant" topics works better.

**Comment by taimurasad** [comment]
I really hope somebody picks up @makleso6 work here and continue to make it over the finish line for AC Freedom-based ACs. While he seemed to have made great progress, it seems he’s busy and doesn’t seem interested in working on it.

**Comment by makleso6** [comment]
Yes I'm really busy. But I'll try to fix it soon.

**Comment by makleso6** [comment]
fix in #1.0.3
