### ISSUE TITLE
AUX J-SMART no response

### ISSUE THREAD

**Issue by mickelk** [makleso6/homebridge-broadlink-heater-cooler#39]
Hey, I have an AUX J-SMART air conditioner with software version v52020. After configuring the add-on, it doesn't work in HomeKit; it doesn't show the temperature, and I can't turn it on.

Is there any way to configure this?

**Comment by makleso6** [comment]
https://github.com/liaan/broadlink_ac_mqtt/issues/61

**Comment by makleso6** [comment]
I don't have AUX air conditioner anymore, so I can't code a new solution.
