### ISSUE TITLE
Accessory details page triggers AC

### ISSUE THREAD

**Issue by ThisIsQasim** [makleso6/homebridge-broadlink-heater-cooler#4]
Whenever I open the details page for my AC by long pressing in the home app it triggers the AC and randomly changes a setting e.g. turn oscillation off/on. Another issue is that if I change the fan speed it enables oscillation. I am guessing the method for getting state is broken. Any help would be appreciated.

**Comment by makleso6** [comment]
I know this bug

**Comment by jackscorpse** [comment]
Well, yesterday I tried to solve this, but that's all i did.
After that part in lib/air-conditioner-api.js:
```
if (fixation_v == 0b00000111) {
    this.status['fixation_v'] = false
} else {
    this.status['fixation_v'] = true
}
```
I added this line:
`this.status['fixation_v'] = 0b00000111;`

So now my AC always in fixed position, oscillation off when I change temperature or open AC page in Home app.
If you want always oscillation on then add:
`this.status['fixation_v'] = 0b00000110;`

This does not completely solve the problem, but as a temporary solution, for now, it's ok.

**Comment by taimurasad** [comment]
> Well, yesterday I tried to solve this, but that's all i did.
> After that part in lib/air-conditioner-api.js:
> 
> ```
> if (fixation_v == 0b00000111) {
>     this.status['fixation_v'] = false
> } else {
>     this.status['fixation_v'] = true
> }
> ```
> 
> I added this line:
> `this.status['fixation_v'] = 0b00000111;`
> 
> So now my AC always in fixed position, oscillation off when I change temperature or open AC page in Home app.
> If you want always oscillation on then add:
> `this.status['fixation_v'] = 0b00000110;`
> 
> This does not completely solve the problem, but as a temporary solution, for now, it's ok.

How did you make this edit when the plugin is already installed on Homebridge instance? Also, did you figure out how to add multiple ACs from AC Freedom to Home app?

**Comment by jackscorpse** [comment]
> How did you make this edit when the plugin is already installed on Homebridge instance? Also, did you figure out how to add multiple ACs from AC Freedom to Home app?

It's in homebridge directory. On Raspberry Pi:
/opt/nodejs/lib/node_modules/homebridge-broadlink-heater-cooler

I'm sorry but I don't know work with multiple ACs.
