### ISSUE TITLE
Multiple ACs?

### ISSUE THREAD

**Issue by taimurasad** [makleso6/homebridge-broadlink-heater-cooler#5]
Hi,

First of all thank you for writing this plugin. I installed it and it worked by showing one AC in Home app but since i have multiple AC units showing in AC Freedom app, i wonder how do i get them all to show up in Home app? Can you please guide?

**Comment by makleso6** [comment]
Support for multiple AC in progress

**Comment by taimurasad** [comment]
Thank you for your work @makleso6 

I have discovered that if you add multiple ACs right now in config file, they do show up but don’t really work properly, likely because they are not identified properly via MAC address.

Here’s my config for multiple ACs

       {
            "accessory": "BroadlinkHeaterCooler",
            "name": "Yellow Room AC",
            "mac": "34:EA:34:96:E3:B7"
        },
        {
            "accessory": "BroadlinkHeaterCooler",
            "name": "Living Room AC",
            "mac": "34:EA:34:8A:D8:4A"
        },
        {
            "accessory": "BroadlinkHeaterCooler",
            "name": "Kitchen AC",
            "mac": "34:EA:34:AA:41:C9"
        },
![iVBORw0KGgoAAAANSUhEUgAAC50AAAjwCAYAAAAKgq9xAAAACXBIWXMAAAsTAAALEwEAmpwYAAAM-2](https://user-images.githubusercontent.com/29396313/82705437-141f2d80-9c91-11ea-8869-04f51555fbe2.png)

If you need testing for multiple ACs, let me know! I will do it! Thank you!

**Comment by taimurasad** [comment]
Hello, any update on multiple AC support man? Thanks > Support for multiple AC in progress

**Comment by makleso6** [comment]
Sorry currently I am busy

**Comment by makleso6** [comment]
Any PR Welcome

**Comment by taimurasad** [comment]
😞 > Sorry currently I am busy

**Comment by taimurasad** [comment]
Any update on this please? 😬 > Sorry currently I am busy

**Comment by taimurasad** [comment]
@makleso6 any update man? Been weeks since last update

**Comment by anat0lich** [comment]
Максим, спасибо за плагин! Тоже очень хочется управлять несколькими сплитами. Оч жду обновления!

**Comment by jackscorpse** [comment]
Тоже хочу поблагодарить за плагин, я долго искал решение для управления своим кондиционером, это пока лучшее, что есть. По mqtt управлять не так удобно и более глючно. Было бы круто развить плагин, но и сейчас все неплохо, если немного подправить код, можно нормально управлять системой.

Интересно, возможно ли заменить этот донгл broadlink на что-то вроде esp8266 и управлять через него?

**Comment by makleso6** [comment]
`Было бы круто развить плагин, но и сейчас все неплохо, если немного подправить код, можно нормально управлять системой.` Да в коде есть много мест, которые можно подправить.

`Интересно, возможно ли заменить этот донгл broadlink на что-то вроде esp8266 и управлять через него?` Уже пытался найти какую либо документацию по wifi свистку, пока безрезультатно. Возможно стоит попробовать подключить свисток напрямую к ПК и дампить.

**Comment by makleso6** [comment]
fix in https://github.com/makleso6/homebridge-broadlink-heater-cooler/releases/tag/1.0.3

**Comment by makleso6** [comment]
@anat0lich @jackscorpse check new update!

**Comment by jackscorpse** [comment]
> @anat0lich @jackscorpse check new update!

Works perfect! Thank you, great work!
