### ISSUE TITLE
Яндекс станция

### ISSUE THREAD

**Issue by kot-925** [makleso6/homebridge-broadlink-heater-cooler#6]
Спасибо за плагин!
Есть один вопрос.
В HomeKit есть практически полное управление, но в у/д Яндекса можно управлять только включить или выключить (написано "это устройство не поддерживает регулировку температуры)

**Comment by makleso6** [comment]
@kot-925 Через какой плагин идет управление для Яндекс станции?

**Comment by kot-925** [comment]
Через Homebridge G On Alice

**Comment by makleso6** [comment]
Возможно будет проще написать отдельный плагин для работы через Алису. Я пока не могу сказать что нужно сделать чтобы через Алису работало, нужно изучать документацию.

**Comment by kot-925** [comment]
Сейчас связка получается такая:
все аксессуары собираются в Homebridge Config UI X(Raspberry) и передаются в
плагин Homebridge G On Alice (Raspberry) который связывается с плагином в у/д Яндекса G-On Homebridge
Блин, наверное косяк в последней цепочки и по ходу дела разработчики забили на него

**Comment by makleso6** [comment]
У Homebridge G On Alice есть поддержка Thermostats но нет поддержки HeaterCooler

**Comment by makleso6** [comment]
Можно использовать API для коммуникации с кондиционером и сделать отдельную обвязка на Thermostats

**Comment by makleso6** [comment]
У Thermostats нет скорости вращения вентиляторов

**Comment by kot-925** [comment]
У них плагин взят за основу от homebridge-alexa , только сильно урезали

**Comment by makleso6** [comment]
@kot-925 Попробуй

**Comment by makleso6** [comment]
@kot-925 попробуй этот плагин, у меня заработало)

**Comment by makleso6** [comment]
https://github.com/makleso6/homebridge-broadlink-thermostat.git

**Comment by kot-925** [comment]
Да этот плагин работает и голосовые команды тоже! Но теперь в homekit  он показывает что всегда работает и температуру в кружочке показывает 0
<img width="114" alt="Снимок экрана 2020-09-24 в 08 34 59" src="https://user-images.githubusercontent.com/13795930/94105512-1ca39280-fe42-11ea-94bb-3400cdae30e9.png">

**Comment by makleso6** [comment]
Да, я еще не успел реализовать обратную связь
