### ISSUE TITLE
Problems with current temperature persists

### ISSUE THREAD

**Issue by fparrav** [makleso6/homebridge-broadlink-heater-cooler#7]
After updating to version [1.0.3](https://github.com/makleso6/homebridge-broadlink-heater-cooler/releases/tag/1.0.3)  it shows the current temperature, but still has erroneous behaviors, sometimes it does not show the correct temperature, showing more than what AC Fredom shows or even showing 0 for a few moments, for now it does not seem to resolve https://github.com/makleso6/homebridge-broadlink-heater-cooler/issues/3

![IMG_2473](https://user-images.githubusercontent.com/9319430/84724250-b1e6df00-af55-11ea-85e5-8cc6d6d91ae4.PNG)

Also when entering to see the device controls it changes the modes and a confirmation beep is heard from the equipment, apparently it is related to this https://github.com/makleso6/homebridge-broadlink-heater-cooler/issues/4 , But I can't put it in heat mode at 21 degrees for example, it automatically switches to "going down to 19" and cold mode is activated

**Comment by makleso6** [comment]
will be fixed in new release

**Comment by makleso6** [comment]
@fparrav check

**Comment by fparrav** [comment]
@makleso6 I just tested it and it works great, plus the device type works better with voice commands than the thermostat. For the moment disable the integration with home assistant since in home assistant it stops working after a while and I have to restart the mqtt client every 2 hours. Many thanks!

**Comment by superpower10** [comment]
I‘m using the newest version but still have this issue. Any ideas?

**Comment by makleso6** [comment]
@superpower10 what is your problem? Can you start a new issue with yours description?
