### ISSUE TITLE
Rotation speed

### ISSUE THREAD

**Issue by makleso6** [makleso6/homebridge-broadlink-heater-cooler#9]
implement get/set Rotation speed

**Comment by fparrav** [comment]
How is the speed set to 'auto'? When I move the slider to the minimum, the device turns off.

**Comment by makleso6** [comment]
Probably it is HomeKit _feature_ (or bug), when you set rotation speed to minimum (0) homekit turn off device.

**Comment by fparrav** [comment]
Is there a way to implement other controls like buttons, with the levels set fixed?

**Comment by makleso6** [comment]
I'll think about it

**Comment by makleso6** [comment]
for auto speed it is possible to create button

**Comment by fparrav** [comment]
A button for the automatic wind would be a good idea, just like the ones that were added in the last update that work excellent!

**Comment by makleso6** [comment]
@fparrav check latest release

**Comment by fparrav** [comment]
It works perfect!  with this all the remote control functions are included in HomeKit, Thanks for this great plugin !!
